'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, CalendarDays, Clock3, FileText, Plus, Check, Send, Pencil, Film, FolderOpen, MessageSquare, ExternalLink, Copy, Link2, ShieldCheck, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { useApp, useResource, useMutation } from '@/lib/api';
import { code, dateLabel, timeLabel, label, inputDate } from '@/lib/utils';
import { Button } from './ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs';
import { Badge, Avatar, ClientMark, Empty, Loading, ErrorState, Field, FormFooter, Modal, Panel, External } from './shared';
import { ContentForm } from './forms';
const actionNames:Record<string,string>={START_SCRIPT:'Start script',SUBMIT_SCRIPT:'Submit script for review',APPROVE:'Approve',REQUEST_CHANGES:'Request changes',START_PRODUCTION:'Start production',SCHEDULE_SHOOT:'Confirm shoot schedule',COMPLETE_SHOOT:'Complete shoot',START_EDITING:'Start editing',SUBMIT_EDIT:'Submit edit for review',READY_TO_PUBLISH:'Mark ready to publish',SCHEDULE_PUBLISH:'Schedule publishing',PUBLISH:'Mark published',ANALYTICS:'Move to analytics',REPORTING:'Move to reporting'};
function actionsFor(c:any,actor:any,can:(p:string)=>boolean){
 const all:Record<string,string[]>={IDEA:['START_SCRIPT'],PLANNING:['START_SCRIPT'],SCRIPT_WRITING:['SUBMIT_SCRIPT'],INTERNAL_SCRIPT_REVIEW:['APPROVE','REQUEST_CHANGES'],CLIENT_SCRIPT_REVIEW:['APPROVE','REQUEST_CHANGES'],SCRIPT_APPROVED:['START_PRODUCTION'],READY_FOR_SHOOT:['SCHEDULE_SHOOT'],SHOOT_SCHEDULED:['COMPLETE_SHOOT'],RAW_FOOTAGE_READY:['START_EDITING'],EDITING:['SUBMIT_EDIT'],INTERNAL_EDIT_REVIEW:['APPROVE','REQUEST_CHANGES'],INTERNAL_APPROVED:['APPROVE','REQUEST_CHANGES'],INTERNAL_CHANGES:['SUBMIT_EDIT'],CLIENT_REVIEW:['APPROVE','REQUEST_CHANGES'],CLIENT_CHANGES:['SUBMIT_EDIT'],FINAL_CLIENT_APPROVED:['READY_TO_PUBLISH'],READY_TO_PUBLISH:['SCHEDULE_PUBLISH','PUBLISH'],SCHEDULED:['PUBLISH'],PUBLISHED:['ANALYTICS'],ANALYTICS:['REPORTING']};
 const team=c.assignees||{};
 return (all[c.status]||[]).filter(action=>{
  if(['APPROVE','REQUEST_CHANGES'].includes(action)){
   if(c.status.startsWith('CLIENT'))return actor.isClient&&can('content.approve_client');
   if(actor.isClient)return false;
   if(c.reviewStage==='SUPER_ADMIN')return actor.isSuperAdmin;
   if(c.reviewStage==='ADMIN')return can('approval.admin');
   return can('content.approve')&&(actor.isSuperAdmin||team.smm===actor.id);
  }
  if(actor.isClient)return false;
  const rule:Record<string,[string,string|undefined]>={START_SCRIPT:['content.edit',team.smm],SUBMIT_SCRIPT:['script.write',team.writer],START_PRODUCTION:['content.edit',team.smm],SCHEDULE_SHOOT:['shoot.manage',team.videographer],COMPLETE_SHOOT:['shoot.manage',team.videographer],START_EDITING:['edit.submit',team.editor||team.designer],SUBMIT_EDIT:['edit.submit',team.editor||team.designer],READY_TO_PUBLISH:['publish.manage',team.smm],SCHEDULE_PUBLISH:['publish.manage',team.smm],PUBLISH:['publish.manage',team.smm],ANALYTICS:['report.manage',team.smm],REPORTING:['report.manage',team.smm]};
  return can(rule[action][0])&&(can('content.edit_all')||rule[action][1]===actor.id||action==='SCHEDULE_SHOOT'&&team.smm===actor.id);
 });
}
export function ContentDetail({id}:{id:number}){
 const {actor,can,openForm}=useApp(),{data:c,loading,error}=useResource('/content/'+id);
 const [tab,setTab]=useState('Overview'),[action,setAction]=useState(''),[edit,setEdit]=useState(false),[version,setVersion]=useState(false);
 const {mutate,pending}=useMutation();
 if(loading)return <Loading/>;if(error)return <ErrorState message={error}/>;if(!c)return null;
 const options=actionsFor(c,actor,can),tabs=actor.isClient?['Overview','Script','Versions','Approvals','Revisions','Drive links','Comments','Publishing']:['Overview','Script','Tasks','Shoot','Drive links','Versions','Approvals','Revisions','Comments','Chat','Publishing','Activity'];
 const editable=can('content.edit')&&!actor.isClient&&(can('content.edit_all')||c.assignees?.smm===actor.id);
 return <><Link className="back-link" href="/content"><ArrowLeft size={14}/> Back to content</Link><div className="content-detail-header"><div className="content-detail-eyebrow"><span>{c.code}</span><i/> <ClientMark name={c.client.name} color={c.client.color} size="tiny"/>{c.client.name}<Badge status={c.status}/></div><div className="page-heading"><h1>{c.title}</h1><div className="heading-actions">{editable&&<Button variant="outline" onClick={()=>setEdit(true)}><Pencil size={14}/> Edit plan</Button>}{options.map(a=><Button key={a} variant={a==='REQUEST_CHANGES'?'outline':'default'} onClick={()=>setAction(a)}>{a==='APPROVE'?<Check size={15}/>:<ArrowUpRight size={15}/>} {actionNames[a]}</Button>)}</div></div><div className="content-detail-meta"><span><CalendarDays size={14}/>{dateLabel(c.publishAt,{day:'numeric',month:'long',year:'numeric'})}</span><span><Clock3 size={14}/>{timeLabel(c.publishAt)}</span><span>{c.platform}</span><span>{c.type}</span>{c.reviewStage&&!actor.isClient&&<span><ShieldCheck size={14}/>{label(c.reviewStage)} review</span>}</div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="content-tabs">{tabs.map(t=><TabsTrigger value={t} key={t}>{t}{c[t.toLowerCase()]?.length>0&&<small>{c[t.toLowerCase()].length}</small>}</TabsTrigger>)}</TabsList>
 <TabsContent value="Overview"><div className="detail-columns"><div><Panel title="The story at a glance" subtitle={c.pillar||'The creative brief'}><div className="prose"><p>{actor.isClient?(c.script?.hook||'Your team is bringing this content to life. Approved scripts and versions will appear here.'):(c.notes||'Add a brief to give your team a clear direction.')}</p></div><dl className="detail-grid"><div><dt>Platform</dt><dd>{c.platform}</dd></div><div><dt>Format</dt><dd>{c.type}</dd></div><div><dt>Content pillar</dt><dd>{c.pillar||'Not set'}</dd></div><div><dt>Publish time</dt><dd>{dateLabel(c.publishAt)} · {timeLabel(c.publishAt)}</dd></div>{!actor.isClient&&<><div><dt>Production</dt><dd>{c.requiresShoot?'Shoot required':'Design / edit'}</dd></div><div><dt>Revision rounds</dt><dd>{c.revisions?.length||0}</dd></div></>}</dl></Panel><Panel title={c.versions?.length?'The latest version':'The next step'}>{c.versions?.length?<div className="version-feature"><span className="version-feature-icon"><Film size={34}/></span><div><span className="eyebrow">VERSION {c.versions[0].number}</span><h3>{c.title}</h3><p>{c.versions[0].notes||'Your latest content, ready for a closer look.'}</p><External href={c.versions[0].driveUrl}>Open in Google Drive</External></div></div>:<div className="next-step"><FileText size={30}/><div><h3>{c.status.includes('SCRIPT')?'Every good story starts with a script.':'Good work is on its way.'}</h3><p>{c.status.includes('SCRIPT')?'Open the Script tab to write, review, or share feedback.':'Your team’s files and progress will appear as the work moves forward.'}</p><Button variant="outline" size="sm" onClick={()=>setTab('Script')}>Open script <ArrowUpRight size={13}/></Button></div></div>}</Panel></div><div>{!actor.isClient&&<><TeamPanel c={c}/><Panel title="The path to publish"><div className="deadline-list">{Object.entries(c.deadlines||{}).map(([key,value])=><div key={key}><span>{label(key.replace(/([A-Z])/g,' $1'))}</span><strong>{dateLabel(value as string)}</strong></div>)}</div></Panel><Panel title="Recent activity"><Timeline items={(c.activities||[]).slice(0,5)}/></Panel></>}</div></div></TabsContent>
 <TabsContent value="Script"><ScriptTab c={c}/></TabsContent>
 {!actor.isClient&&<><TabsContent value="Tasks"><Panel title="The work behind this content" action={can('task.create')&&<Button size="sm" variant="outline" onClick={()=>openForm('task',{clientId:c.clientId,contentId:c.id})}><Plus size={14}/> Add task</Button>}>{c.tasks?.length?<div className="table-scroll"><table><thead><tr><th>Task</th><th>Assigned to</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{c.tasks.map((t:any)=><tr key={t.id}><td><Link className="text-link" href={'/tasks?task='+t.id}>{t.title}<ArrowUpRight size={14}/></Link></td><td>{t.assignee.name}</td><td>{dateLabel(t.dueAt)}</td><td><Badge status={t.status}/></td></tr>)}</tbody></table></div>:<Empty title="No tasks yet"/>}</Panel></TabsContent><TabsContent value="Shoot"><ShootTab c={c}/></TabsContent></>}
 <TabsContent value="Drive links"><Panel title="Everything has a home" subtitle="Files live in Google Drive. Their context lives here." action={can('drive.manage')&&<Button size="sm" variant="outline" onClick={()=>openForm('drive',{clientId:c.clientId,contentId:c.id})}><Plus size={14}/> Add link</Button>}>{c.driveLinks?.length?<div className="link-list">{c.driveLinks.map((l:any)=><div key={l.id}><FolderOpen size={20}/><div><strong>{l.title}</strong><small>{l.category}{!actor.isClient&&(l.clientVisible?' · Client visible':' · Internal only')}</small></div><External href={l.url}>Open in Drive</External></div>)}</div>:<Empty title="Links, neatly connected" body="Brand assets, references, and final files will appear here."/>}</Panel></TabsContent>
 <TabsContent value="Versions"><Panel title="Every version, preserved" subtitle="A record of how the work came together." action={can('edit.submit')&&['EDITING','INTERNAL_CHANGES','CLIENT_CHANGES'].includes(c.status)&&<Button size="sm" onClick={()=>setVersion(true)}><Plus size={14}/> Add version</Button>}>{c.versions?.length?<div className="versions-list">{c.versions.map((v:any)=><div key={v.id}><span className="version-number">V{v.number}</span><div><strong>{v.number===c.versions[0].number?'Latest version':'Previous version'}</strong><p>{v.notes||'No additional notes.'}</p><small>{v.addedBy?.name&&v.addedBy.name+' · '}{dateLabel(v.createdAt)} · {timeLabel(v.createdAt)}</small></div><div>{!actor.isClient&&<Badge status={v.clientVisible?'APPROVED':'INTERNAL_EDIT_REVIEW'}>{v.clientVisible?'Shared with client':'Internal'}</Badge>}<External href={v.driveUrl}>Open version</External></div></div>)}</div>:<Empty title="Your first cut starts here" body="Add a Google Drive link when the first version is ready."/>}</Panel></TabsContent>
 <TabsContent value="Approvals"><Panel title="A clear record of every decision">{c.approvals?.length?<div className="approval-history">{c.approvals.map((a:any)=><div key={a.id}><span className={'decision-icon '+(a.decision==='APPROVED'?'green':'amber')}><ShieldCheck size={18}/></span><div><strong>{label(a.stage)} <span>· {a.reviewer?.name}</span></strong><p>{a.comment||label(a.decision)}</p><small>{dateLabel(a.createdAt)} · {timeLabel(a.createdAt)}</small></div><Badge status={a.decision}/></div>)}</div>:<Empty title="The review journey starts here" body="Every approval and change request will be recorded as the content progresses."/>}</Panel></TabsContent>
 <TabsContent value="Revisions"><Panel title="Feedback that moves the work forward">{c.revisions?.length?<div className="revision-list">{c.revisions.map((r:any)=><div className="revision-card" key={r.id}><div><strong>Revision {r.number}</strong><Badge status={r.status==='OPEN'?'CHANGES_REQUIRED':'COMPLETED'}/></div><p>{r.comments}</p>{r.timestampComments?.map((t:any,i:number)=><p className="timestamp-note" key={i}><code>{t.timestamp}</code>{t.comment}</p>)}{r.referenceUrls?.map((u:string,i:number)=><External key={u} href={u}>Reference {i+1}</External>)}{r.resolution&&<p className="resolution-note">{r.resolution}</p>}<small>{r.requestedBy?.name&&r.requestedBy.name+' · '}{dateLabel(r.createdAt)}{r.assignee&&' · Assigned to '+r.assignee.name}</small></div>)}</div>:<Empty title="Looking good so far" body="Revision requests and feedback with timestamps will appear here."/>}</Panel></TabsContent>
 <TabsContent value="Comments"><Comments c={c}/></TabsContent>{!actor.isClient&&<TabsContent value="Chat"><ContentChat c={c}/></TabsContent>}
 <TabsContent value="Publishing"><PublishingTab c={c}/></TabsContent>{!actor.isClient&&<TabsContent value="Activity"><Panel title="The full story" subtitle="Every important change, in order."><Timeline items={c.activities||[]}/>{c.history?.length>0&&<div className="status-history">{c.history.map((h:any)=><div key={h.id}><Badge status={h.previous}/><ChevronRight size={13}/><Badge status={h.next}/><time>{dateLabel(h.createdAt)} · {timeLabel(h.createdAt)}</time></div>)}</div>}</Panel></TabsContent>}</Tabs>
 <Modal open={edit} onOpenChange={setEdit} title="Update the content plan" wide>{edit&&<ContentForm initial={c} onDone={()=>setEdit(false)}/>}</Modal>
 <Modal open={!!action} onOpenChange={v=>!v&&setAction('')} title={actionNames[action]||'Update workflow'} description={action==='REQUEST_CHANGES'?'Make your feedback specific so the team knows what to improve.':'The linked tasks, calendar status, and notifications will update together.'}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload:any={action,revision:c.revision};for(const key of ['comment','rawUrl','publishedUrl','externalPostId'])if(f.get(key))payload[key]=f.get(key);if(f.get('scheduledAt'))payload.scheduledAt=new Date(f.get('scheduledAt') as string).toISOString();if(f.get('timestamps'))payload.timestampComments=String(f.get('timestamps')).split('\n').filter(Boolean).map(line=>{const [timestamp,...rest]=line.trim().split(' ');return {timestamp,comment:rest.join(' ')};});if(f.get('references'))payload.referenceUrls=String(f.get('references')).split('\n').map(s=>s.trim()).filter(Boolean);try{await mutate('/content/'+id+'/actions',payload,'POST','Workflow updated');setAction('');}catch{}}}>
 {action==='COMPLETE_SHOOT'&&<Field label="Raw footage Drive URL"><input type="url" name="rawUrl" required placeholder="https://drive.google.com/…"/></Field>}{action==='PUBLISH'&&<><Field label="Published post URL"><input name="publishedUrl" type="url" required placeholder="https://www.instagram.com/p/…"/></Field><Field label="External post ID (optional)"><input name="externalPostId"/></Field></>}{action==='SCHEDULE_PUBLISH'&&<><Field label="Publish date & time"><input name="scheduledAt" type="datetime-local" required defaultValue={inputDate(c.publishAt)}/></Field><p className="info-note">This schedules your team’s publishing workflow. Your SMM publishes the post on the platform and records its URL here.</p></>}
 <Field label={action==='REQUEST_CHANGES'?'What needs to change?':'Comment (optional)'}><textarea name="comment" rows={3} required={action==='REQUEST_CHANGES'} placeholder={action==='APPROVE'?'Looking good. Let’s move this forward.':'Add helpful context…'}/></Field>{action==='REQUEST_CHANGES'&&<><Field label="Timestamp feedback" hint="One per line, for example: 00:14 Replace this clip."><textarea rows={3} name="timestamps" placeholder={'00:14 Replace this clip.\n00:31 Make the logo smaller.'}/></Field><Field label="Reference URLs" hint="One URL per line."><textarea rows={2} name="references" placeholder="https://…"/></Field></>}<FormFooter pending={pending} onCancel={()=>setAction('')} submit={actionNames[action]}/></form></Modal>
 <Modal open={version} onOpenChange={setVersion} title="Add the next version" description="Previous versions stay preserved. This version will go through internal review."><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate('/content/'+id+'/versions',{url:f.get('url'),notes:f.get('notes'),revision:c.revision},'POST','New version added');setVersion(false);}catch{}}}><Field label="Video / cut URL"><input name="url" type="url" required placeholder="https://…"/></Field><Field label="What changed?"><textarea name="notes" rows={3}/></Field><FormFooter pending={pending} onCancel={()=>setVersion(false)} submit="Add version"/></form></Modal>
 </>;
}
function TeamPanel({c}:{c:any}){const {data:users}=useResource<any[]>('/users');return <Panel title="The people behind it"><div className="content-team">{Object.entries(c.assignees||{}).map(([role,id])=>{const user=users?.find(u=>u.id===id);return <div key={role}><Avatar name={user?.name||'?'} color={user?.avatarColor} src={user?.avatarUrl} size="small"/><span><strong>{user?.name||'Team member'}</strong><small>{role==='smm'?'Social media manager':label(role)}</small></span></div>;})}</div></Panel>;}
function ScriptTab({c}:{c:any}){
 const {actor,can}=useApp(),{mutate,pending}=useMutation();
 const editable=!actor.isClient&&can('script.write')&&(can('content.edit_all')||c.assignees?.writer===actor.id)&&['PLANNING','SCRIPT_WRITING'].includes(c.status);
 const s=c.script||{};
 return <Panel title={editable?'Shape the story':'The script'} subtitle={editable?'Save your draft, then submit it for review when you’re ready.':actor.isClient?'The latest script shared by your agency.':'A single brief for everyone creating this content.'}>
 {!c.script&&!editable?<Empty title="The story is taking shape" body="Your script will appear here when it’s ready to share."/>:<form className="script-form" key={s.updatedAt||'script'} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate('/content/'+c.id+'/script',{hook:f.get('hook'),body:f.get('body'),cta:f.get('cta'),caption:f.get('caption'),hashtags:f.get('hashtags'),references:String(f.get('references')||'').split('\n').map(s=>s.trim()).filter(Boolean),notes:f.get('notes')||'',revision:c.revision},'POST','Draft saved');}catch{}}}>{[['hook','The hook','One line to make them stop scrolling.',3],['body','Main script','The story, beat by beat.',10],['cta','Call to action','What should they do next?',2],['caption','Caption','The words that go with the content.',4],['hashtags','Hashtags','',2]].map(([key,title,hint,rows])=><Field key={key} label={title as string} hint={editable?hint as string:undefined}><textarea name={key as string} rows={rows as number} defaultValue={s[key as string]||''} readOnly={!editable} className={!editable?'read-only':''}/></Field>)}{editable?<><Field label="Reference URLs" hint="One URL per line."><textarea name="references" rows={2} defaultValue={s.references?.join('\n')} placeholder="https://…"/></Field><Field label="Internal notes"><textarea name="notes" rows={2} defaultValue={s.notes}/></Field><FormFooter pending={pending} submit="Save draft"/></>:<div className="reference-links">{s.references?.map((r:string,i:number)=><External href={r} key={r}>Reference {i+1}</External>)}</div>}</form>}
 </Panel>;
}
function ShootTab({c}:{c:any}){
 const {actor,can}=useApp(),{mutate,pending}=useMutation(),s=c.shoot||{};
 const edit=can('shoot.manage')&&(can('content.edit_all')||[c.assignees?.smm,c.assignees?.videographer].includes(actor.id))&&['READY_FOR_SHOOT','SHOOT_SCHEDULED'].includes(c.status);
 if(!c.requiresShoot)return <Panel title="Production route"><Empty title="No shoot needed" body="This content goes from script approval directly to design or editing."/></Panel>;
 return <Panel title="Shoot plan" subtitle="Everything the videographer needs for a good day on set."><form className="padded-form" key={s.updatedAt} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d:any={scheduledAt:new Date(f.get('scheduledAt') as string).toISOString(),location:f.get('location'),shotList:f.get('shotList'),props:f.get('props'),people:f.get('people'),orientation:f.get('orientation'),durationMinutes:Number(f.get('durationMinutes')),notes:f.get('notes')};if(f.get('referenceUrl'))d.referenceUrl=f.get('referenceUrl');try{await mutate('/content/'+c.id+'/shoot',d,'POST','Shoot plan saved');}catch{}}}><div className="form-grid"><Field label="Date & time"><input type="datetime-local" name="scheduledAt" required defaultValue={inputDate(s.scheduledAt||c.deadlines?.shoot||new Date())} readOnly={!edit}/></Field><Field label="Location"><input name="location" defaultValue={s.location||''} required readOnly={!edit}/></Field><Field label="Orientation"><select name="orientation" defaultValue={s.orientation||'Portrait'} disabled={!edit}>{['Portrait','Landscape','Square'].map(o=><option key={o}>{o}</option>)}</select></Field><Field label="Estimated duration (minutes)"><input type="number" min={1} max={1440} name="durationMinutes" defaultValue={s.durationMinutes||60} readOnly={!edit}/></Field></div>{[['shotList','Shot list'],['props','Props'],['people','People required'],['referenceUrl','Reference URL'],['notes','Internal notes']].map(([key,title])=><Field key={key} label={title}><textarea rows={key==='shotList'?4:2} name={key} defaultValue={s[key]||''} readOnly={!edit} required={key==='shotList'}/></Field>)}{edit&&<FormFooter pending={pending} submit="Save shoot plan"/>}</form></Panel>;
}
function Comments({c}:{c:any}){const {actor}=useApp(),{mutate,pending}=useMutation();return <Panel title="Keep the conversation in context"><div className="comment-list">{c.comments?.map((m:any)=><div key={m.id}><Avatar name={m.author.name} color={m.author.avatarColor} src={m.author.avatarUrl} size="small"/><div><strong>{m.author.name}</strong><small>{dateLabel(m.createdAt)} {!actor.isClient&&(m.clientVisible?'· Client visible':'· Internal')}</small><p>{m.body}</p>{m.timestamp&&<code>{m.timestamp}</code>}{m.referenceUrl&&<External href={m.referenceUrl}>Reference</External>}</div></div>)}{!c.comments?.length&&<Empty title="Start a conversation" body="Keep the context close to the work."/ >}</div><form className="comment-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const d:any={body:f.get('body'),clientVisible:actor.isClient||f.get('clientVisible')==='on'};if(f.get('timestamp'))d.timestamp=f.get('timestamp');if(f.get('referenceUrl'))d.referenceUrl=f.get('referenceUrl');try{await mutate('/content/'+c.id+'/comments',d,'POST','Comment added');form.reset();}catch{}}}><Field label="Your comment"><textarea name="body" required rows={3} placeholder="Add a thought, a question, or a little context…"/></Field><div className="form-grid"><Field label="Timestamp (optional)"><input name="timestamp" placeholder="00:14"/></Field><Field label="Reference URL (optional)"><input name="referenceUrl" type="url" placeholder="https://…"/></Field></div>{!actor.isClient&&<label className="checkbox-label"><input type="checkbox" name="clientVisible"/> Share this comment with the client</label>}<FormFooter pending={pending} submit="Add comment"/></form></Panel>;}
function ContentChat({c}:{c:any}){const {data}=useResource<any[]>('/chat');const thread=data?.find(t=>t.clientId===c.clientId&&t.kind==='CLIENT_INTERNAL')||data?.find(t=>t.clientId===c.clientId)||data?.find(t=>t.contentId===c.id);return <Panel title="Client conversation" subtitle="Team conversations for this client are kept unified in the client thread."><div className="next-step"><MessageSquare size={32}/><div><h3>{thread?.title||c.client?.name+' · internal'}</h3><p>{thread?'All discussion and updates for this content flow directly into the client conversation thread.':'Open the conversation to keep the team aligned.'}</p><Link href={thread?'/chat?thread='+thread.id:'/chat'}><Button>Open conversation <ArrowUpRight size={15}/></Button></Link></div></div></Panel>;}
function PublishingTab({c}:{c:any}){
 const {can}=useApp();return <><Panel title="Ready for the world" subtitle="Publish on your chosen platform, then record the live URL here.">{c.publishing?<div className="padded-form"><dl className="detail-grid"><div><dt>Status</dt><dd><Badge status={c.publishing.status}/></dd></div><div><dt>Platform</dt><dd>{c.platform}</dd></div><div><dt>Scheduled for</dt><dd>{dateLabel(c.publishing.scheduledAt||c.publishAt)} · {timeLabel(c.publishing.scheduledAt||c.publishAt)}</dd></div><div><dt>Final file</dt><dd><External href={c.publishing.finalDriveUrl}>Open in Drive</External></dd></div></dl><Field label="Caption"><textarea rows={4} readOnly value={c.publishing.caption}/></Field><Field label="Hashtags"><textarea rows={2} readOnly value={c.publishing.hashtags}/></Field><Button variant="outline" onClick={()=>navigator.clipboard.writeText(c.publishing.caption+'\n\n'+c.publishing.hashtags).then(()=>toast.success('Caption copied')).catch(()=>toast.error('Select the caption and copy it manually.'))}><Copy size={14}/> Copy caption & hashtags</Button>{c.publishing.publishedUrl&&<p className="published-url"><External href={c.publishing.publishedUrl}>View published post</External></p>}</div>:<Empty title="A few steps before the spotlight" body="Publishing details become available after the required approvals are complete."/>}</Panel>{can('report.manage')&&['PUBLISHED','ANALYTICS','REPORTING'].includes(c.status)&&<MetricsForm c={c}/>}</>;
}
export function MetricsForm({c}:{c:any}){const {mutate,pending}=useMutation();return <Panel title="How did it do?" subtitle="Record cumulative metrics for this post. Reports use its latest snapshot."><form className="padded-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),d:any={};for(const [k,v]of f)d[k]=k==='date'?new Date(String(v)).toISOString():Number(v);try{await mutate('/content/'+c.id+'/metrics',d,'POST','Metrics saved');}catch{}}}><Field label="Snapshot date"><input type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><div className="form-grid three">{['reach','impressions','views','likes','comments','shares','saves','followerGrowth'].map(k=><Field key={k} label={label(k.replace(/([A-Z])/g,' $1'))}><input type="number" name={k} min={k==='followerGrowth'?undefined:0} defaultValue={c.metrics?.[0]?.[k]||0} required/></Field>)}</div><FormFooter pending={pending} submit="Save metrics"/></form></Panel>;}
export function Timeline({items}:{items:any[]}){if(!items.length)return <Empty title="A clean page" body="Important updates will be recorded here."/>;return <div className="timeline">{items.map((a:any)=><div key={a.id}><span className="timeline-point"/><div><strong>{label(a.action.replaceAll('.',' '))}</strong><p>{a.actor?.name||'Agency OS'}{a.client?.name&&' · '+a.client.name}</p><time>{dateLabel(a.createdAt)} · {timeLabel(a.createdAt)}</time></div></div>)}</div>;}

