'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, ChevronLeft, ChevronRight, CalendarDays } from 'lucide-react';
import { useMutation, useResource, useApp } from '@/lib/api';
import { inputDate, label } from '@/lib/utils';
import { Button } from './ui/button';
import { Field, FormFooter, Loading, ErrorState, ImageUploadField, ColorPickerField } from './shared';
const offsets={script:8,clientScript:7,shoot:5,edit:3,internal:3,clientFinal:2,ready:1};
const deadlines=(at:string,values:any=offsets)=>Object.fromEntries(Object.entries(values).map(([key,days])=>[key,new Date(new Date(at).getTime()-Number(days)*86400000).toISOString()]));
const emptyBrand={colors:'',fonts:'',logoUrl:'',assetsUrl:'',audience:'',competitors:'',pillars:'',tone:'',dos:'',donts:''};
const responsibilities=['smm','writer','designer','editor','videographer'];
export function CreateForm({kind,initial,onDone}:{kind:string;initial?:any;onDone:()=>void}){
 if(kind==='client')return <ClientForm initial={initial} onDone={onDone}/>;
 if(kind==='user')return <UserForm initial={initial} onDone={onDone}/>;
 if(kind==='profile')return <ProfileForm onDone={onDone}/>;
 if(kind==='task')return <TaskForm initial={initial} onDone={onDone}/>;
 if(kind==='drive')return <DriveForm initial={initial} onDone={onDone}/>;
 return <ContentForm initial={initial} onDone={onDone}/>;
}
export function ContentForm({initial,onDone}:{initial?:any;onDone:()=>void}){
 const {mutate,pending}=useMutation(),router=useRouter();
 const {data:clients,loading,error}=useResource<any[]>('/clients');
 const [d,setD]=useState<any>({clientId:'',title:'',platform:'Instagram',type:'Instagram Reel',pillar:'',publishAt:new Date(Date.now()+8*86400000).toISOString(),requiresShoot:false,assignees:{},notes:'',...initial});
 const {data:client}=useResource(d.clientId?'/clients/'+d.clientId:null);
 const [dates,setDates]=useState<any>(initial?.deadlines||deadlines(d.publishAt));
 useEffect(()=>{if(client&&!initial?.id){const team:any={};for(const r of responsibilities)team[r]=client.team?.find((t:any)=>t.responsibility===r)?.userId||'';setD((v:any)=>({...v,assignees:team}));setDates(deadlines(d.publishAt,client.deadlineOffsets));}},[client?.id]);
 const set=(key:string,value:any)=>setD((v:any)=>({...v,[key]:value}));
 if(loading)return <Loading/>;if(error)return <ErrorState message={error}/>;
 return <form onSubmit={async e=>{e.preventDefault();const payload={title:d.title,platform:d.platform,type:d.type,pillar:d.pillar||'',publishAt:d.publishAt,requiresShoot:d.requiresShoot,assignees:Object.fromEntries(Object.entries(d.assignees).filter(([,v])=>v)),notes:d.notes||'',deadlines:dates};try{const result=await mutate(initial?.id?'/content/'+initial.id:'/content',initial?.id?{...payload,revision:initial.revision}:{...payload,clientId:d.clientId},initial?.id?'PATCH':'POST',initial?.id?'Content plan updated':'Your new content is ready');onDone();if(!initial?.id)router.push('/content/'+result.id);}catch{}}}>
 <div className="form-grid"><Field label="Client"><select value={d.clientId} onChange={e=>set('clientId',e.target.value)} required disabled={!!initial?.id}><option value="">Choose a client</option>{clients?.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Content title"><input value={d.title} onChange={e=>set('title',e.target.value)} required minLength={3} maxLength={300} placeholder="Give this story a name"/></Field><Field label="Platform"><select value={d.platform} onChange={e=>set('platform',e.target.value)}>{['Instagram','Facebook','YouTube','LinkedIn','Google Business Profile','Other'].map(p=><option key={p}>{p}</option>)}</select></Field><Field label="Format"><input list="content-formats" value={d.type} onChange={e=>set('type',e.target.value)} required/><datalist id="content-formats">{['Instagram Reel','Facebook Reel','YouTube Short','Long Video','Static Post','Carousel','Story','LinkedIn Post','Other Custom Type'].map(t=><option key={t}>{t}</option>)}</datalist></Field><Field label="Content pillar"><input value={d.pillar||''} onChange={e=>set('pillar',e.target.value)} placeholder="Education, brand stories, community…"/></Field><Field label="Publish date & time" hint="Shown in your device’s local timezone."><input type="datetime-local" required value={inputDate(d.publishAt)} onChange={e=>e.target.value&&set('publishAt',new Date(e.target.value).toISOString())}/></Field></div>
 <div className="form-section-title">The team behind it</div><div className="form-grid three">{responsibilities.map(r=><Field key={r} label={r==='smm'?'Social media manager':label(r)}><select value={d.assignees?.[r]||''} required={r==='smm'} onChange={e=>set('assignees',{...d.assignees,[r]:e.target.value})}><option value="">{r==='smm'?'Choose your SMM':'Assign later'}</option>{client?.team?.filter((t:any,i:number,arr:any[])=>arr.findIndex(x=>x.userId===t.userId)===i).map((t:any)=><option key={t.userId} value={t.userId}>{t.user.name}</option>)}</select></Field>)}</div><label className="checkbox-label"><input type="checkbox" checked={d.requiresShoot} onChange={e=>set('requiresShoot',e.target.checked)}/> This content needs a shoot</label>
 <div className="form-section-title">Work backwards from publish day<Button type="button" variant="ghost" size="sm" onClick={()=>setDates(deadlines(d.publishAt,client?.deadlineOffsets||offsets))}><CalendarDays size={13}/> Suggest deadlines</Button></div><div className="form-grid three">{Object.entries(dates).map(([key,value])=><Field label={label(key.replace(/([A-Z])/g,' $1'))} key={key}><input type="datetime-local" required value={inputDate(value as string)} onChange={e=>e.target.value&&setDates({...dates,[key]:new Date(e.target.value).toISOString()})}/></Field>)}</div><Field label="Internal brief & notes"><textarea value={d.notes||''} onChange={e=>set('notes',e.target.value)} rows={3} placeholder="What should the team know?"/></Field><FormFooter pending={pending} onCancel={onDone} submit={initial?.id?'Save content plan':'Create content'}/></form>;
}
function ClientForm({initial,onDone}:{initial?:any;onDone:()=>void}){
 const {mutate,pending}=useMutation(),{data:users}=useResource<any[]>('/users'),router=useRouter();
 const [step,setStep]=useState(0),[createLogin,setCreateLogin]=useState(false),[login,setLogin]=useState({name:'',email:'',password:'',avatarUrl:''});
 const [d,setD]=useState<any>({name:'',industry:'',website:'',contactName:'',email:'',phone:'',whatsapp:'',address:'',packageName:'Growth',deliverables:{Reels:8,Posts:8,Stories:12},platforms:['Instagram'],notes:'',color:'#0284c7',avatarUrl:null,team:[],approvalRules:{smm:true,admin:false,superAdmin:false,client:true},deadlineOffsets:offsets,socialAccounts:initial?.accounts||[],...initial,brand:{...emptyBrand,...initial?.brand}});
 const set=(k:string,v:any)=>setD((x:any)=>({...x,[k]:v}));
 const fields=(entries:string[][])=>entries.map(([key,title,type])=><Field key={key} label={title}><input type={type||'text'} value={d[key]||''} onChange={e=>set(key,e.target.value)} required={['name','industry','contactName','email'].includes(key)} minLength={['name','contactName'].includes(key)?2:undefined}/></Field>);
 return <form onSubmit={async e=>{e.preventDefault();if(step<4){setStep(s=>s+1);return;}const payload:any=Object.fromEntries(['name','industry','website','contactName','email','phone','whatsapp','address','packageName','deliverables','platforms','brand','notes','color','avatarUrl','approvalRules','deadlineOffsets'].map(k=>[k,d[k]]));payload.team=d.team.map((t:any)=>({userId:t.userId,responsibility:t.responsibility}));payload.socialAccounts=d.socialAccounts.map((s:any)=>({platform:s.platform,handle:s.handle,url:s.url||''}));if(createLogin&&!initial?.id)payload.login={name:login.name,email:login.email,password:login.password,...(login.avatarUrl?{avatarUrl:login.avatarUrl}:{})};try{const result=await mutate(initial?.id?'/clients/'+initial.id:'/clients',payload,initial?.id?'PATCH':'POST',initial?.id?'Client workspace updated':'A new client workspace is ready');onDone();if(!initial?.id)router.push('/clients/'+result.id);}catch{}}}>
 <div className="wizard-steps">{['The basics','The plan','The brand','The team','The workspace'].map((s,i)=><div key={s} className={`wizard-step ${step===i?'active':step>i?'complete':''}`} onClick={()=>setStep(i)} role="button" tabIndex={0}><span className="step-num">{step>i?<Check size={12} strokeWidth={2.5}/>:i+1}</span><small className="step-label">{s}</small></div>)}</div>
 {step===0&&<><h3>Let’s get to know them.</h3><ImageUploadField label="Brand logo / mark" value={d.avatarUrl} onChange={v=>set('avatarUrl',v)} name={d.name||'Brand'} shape="square" hint="Client mark shown across workspace cards and headers"/><div className="form-grid">{fields([['name','Company name'],['industry','Industry'],['website','Website','url'],['contactName','Primary contact'],['email','Contact email','email'],['phone','Phone','tel'],['whatsapp','WhatsApp number','tel'],['address','Address']])}</div><ColorPickerField value={d.color} onChange={v=>set('color',v)}/></>}
 {step===1&&<><h3>What are we creating together?</h3><Field label="Monthly package"><input value={d.packageName} onChange={e=>set('packageName',e.target.value)} required/></Field><div className="form-grid three">{Object.entries(d.deliverables).map(([key,value])=><Field key={key} label={key+' per month'}><input type="number" min={0} max={10000} value={value as number} onChange={e=>set('deliverables',{...d.deliverables,[key]:Number(e.target.value)})}/></Field>)}</div><div className="form-section-title">Platforms</div><div className="checkbox-grid">{['Instagram','Facebook','YouTube','LinkedIn','Google Business Profile'].map(p=><label className="checkbox-label" key={p}><input type="checkbox" checked={d.platforms.includes(p)} onChange={e=>set('platforms',e.target.checked?[...d.platforms,p]:d.platforms.filter((x:string)=>x!==p))}/>{p}</label>)}</div>{d.platforms.map((p:string)=><Field key={p} label={p+' handle'}><input placeholder="@brandname" value={d.socialAccounts.find((s:any)=>s.platform===p)?.handle||''} onChange={e=>set('socialAccounts',[...d.socialAccounts.filter((s:any)=>s.platform!==p),{platform:p,handle:e.target.value}])}/></Field>)}</>}
 {step===2&&<><h3>A feel for their world.</h3><div className="form-grid">{Object.entries({colors:'Brand colors',fonts:'Fonts',logoUrl:'Logo Drive URL',assetsUrl:'Brand assets Drive URL',audience:'Target audience',competitors:'Competitors',pillars:'Content pillars',tone:'Brand tone',dos:'Brand do’s',donts:'Brand don’ts'}).map(([key,title])=><Field key={key} label={title}>{['audience','dos','donts'].includes(key)?<textarea rows={2} value={d.brand[key]} onChange={e=>set('brand',{...d.brand,[key]:e.target.value})}/>:<input value={d.brand[key]} type={key.endsWith('Url')?'url':'text'} onChange={e=>set('brand',{...d.brand,[key]:e.target.value})}/>}</Field>)}</div></>}
 {step===3&&<><h3>Bring the right people together.</h3><p className="muted">The dedicated SMM will coordinate content, reviews, and publishing.</p><div className="form-grid">{[...responsibilities,'other'].map(r=><Field key={r} label={r==='smm'?'Dedicated social media manager':label(r)}><select required={r==='smm'} value={d.team.find((t:any)=>t.responsibility===r)?.userId||''} onChange={e=>set('team',[...d.team.filter((t:any)=>t.responsibility!==r),...(e.target.value?[{userId:e.target.value,responsibility:r}]:[])])}><option value="">Choose a team member</option>{users?.filter(u=>u.active&&!u.role.isClient).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role.name}</option>)}</select></Field>)}</div><Field label="Internal notes"><textarea rows={3} value={d.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></>}
 {step===4&&<><div className="onboarding-summary"><span style={{background:d.color}}>{d.name.slice(0,1)}</span><div><h3>{d.name||'Your new client'}</h3><p>{d.packageName} · {d.platforms.join(', ')}</p></div></div><div className="form-section-title">Their approval journey</div><div className="checkbox-grid">{Object.entries({smm:'SMM review (always required)',admin:'Admin review',superAdmin:'Super Admin review',client:'Client review'}).map(([key,title])=><label className="checkbox-label" key={key}><input type="checkbox" disabled={key==='smm'} checked={d.approvalRules[key]} onChange={e=>set('approvalRules',{...d.approvalRules,[key]:e.target.checked})}/>{title}</label>)}</div><div className="form-section-title">Deadline defaults <small>Days before publishing</small></div><div className="form-grid three">{Object.entries(d.deadlineOffsets).map(([key,value])=><Field key={key} label={label(key.replace(/([A-Z])/g,' $1'))}><input type="number" min={0} max={365} value={value as number} onChange={e=>set('deadlineOffsets',{...d.deadlineOffsets,[key]:Number(e.target.value)})}/></Field>)}</div>{!initial?.id&&<><label className="checkbox-label"><input type="checkbox" checked={createLogin} onChange={e=>{setCreateLogin(e.target.checked);setLogin(v=>({...v,name:d.contactName,email:d.email}));}}/>Create the client’s login now</label>{createLogin&&<div className="form-grid"><ImageUploadField label="Client profile image" value={login.avatarUrl} onChange={val=>setLogin(l=>({...l,avatarUrl:val||''}))} name={login.name||d.contactName||'Client'} hint="Visible in the client's profile widget and topbar when they sign in"/>{Object.entries({name:'Client’s name',email:'Login email',password:'Temporary password (12+ characters)'}).map(([key,title])=><Field key={key} label={title}><input type={key==='password'?'password':key==='email'?'email':'text'} minLength={key==='password'?12:undefined} value={(login as any)[key]} required onChange={e=>setLogin({...login,[key]:e.target.value})}/></Field>)}<p className="muted full-width">Share the temporary credentials securely. The client will choose a new password on first sign-in.</p></div>}</>}</>}
 <div className="form-footer">{step>0?<Button variant="outline" type="button" onClick={()=>setStep(s=>s-1)}><ChevronLeft size={15}/> Back</Button>:<Button variant="outline" type="button" onClick={onDone}>Cancel</Button>}<Button disabled={pending} type="submit">{pending?'Saving…':step<4?'Continue':initial?.id?'Save workspace':'Create workspace'}<ChevronRight size={15}/></Button></div></form>;
}
function TaskForm({initial,onDone}:{initial?:any;onDone:()=>void}){
 const {actor}=useApp(),{mutate,pending}=useMutation(),{data:clients}=useResource<any[]>('/clients'),{data:users}=useResource<any[]>('/users'),{data:content}=useResource<any[]>('/content');
 const [client,setClient]=useState(initial?.clientId||'');
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d:any={title:f.get('title'),description:f.get('description'),clientId:client,assigneeId:f.get('assigneeId'),priority:f.get('priority'),dueAt:new Date(f.get('dueAt') as string).toISOString()};if(f.get('startsAt'))d.startsAt=new Date(f.get('startsAt') as string).toISOString();if(f.get('contentId'))d.contentId=Number(f.get('contentId'));if(f.get('driveUrl'))d.driveUrl=f.get('driveUrl');try{await mutate('/tasks',d,'POST','Task assigned');onDone();}catch{}}}>
 <Field label="Task title"><input name="title" minLength={3} required placeholder="What needs to happen?"/></Field><Field label="Description"><textarea name="description" rows={3}/></Field><div className="form-grid"><Field label="Client"><select value={client} onChange={e=>setClient(e.target.value)} required><option value="">Choose a client</option>{clients?.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Related content"><select name="contentId" defaultValue={initial?.contentId||''}><option value="">General client task</option>{content?.filter(c=>c.clientId===client).map(c=><option key={c.id} value={c.id}>{c.code} · {c.title}</option>)}</select></Field><Field label="Assign to"><select name="assigneeId" required><option value="">Choose a person</option>{users?.filter(u=>u.active&&!u.role.isClient&&(!u.role.isSuperAdmin||actor.isSuperAdmin)&&(u.role.isSuperAdmin||u.teams.some((t:any)=>t.clientId===client))).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Priority"><select name="priority" defaultValue="MEDIUM">{['LOW','MEDIUM','HIGH','URGENT'].map(p=><option value={p} key={p}>{label(p)}</option>)}</select></Field><Field label="Start date"><input type="datetime-local" name="startsAt"/></Field><Field label="Deadline"><input name="dueAt" type="datetime-local" required defaultValue={inputDate(new Date(Date.now()+86400000))}/></Field></div><Field label="Reference URL"><input type="url" name="driveUrl" placeholder="https://…"/></Field><FormFooter pending={pending} onCancel={onDone} submit="Create & assign task"/></form>;
}
function DriveForm({initial,onDone}:{initial?:any;onDone:()=>void}){
 const {mutate,pending}=useMutation(),{data:clients}=useResource<any[]>('/clients'),{data:content}=useResource<any[]>('/content'),{data:tasks}=useResource<any[]>('/tasks');
 const [client,setClient]=useState(initial?.clientId||''),[cid,setCid]=useState(String(initial?.contentId||''));
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d:any={clientId:client,title:f.get('title'),url:f.get('url'),category:f.get('category'),clientVisible:f.get('clientVisible')==='on'};if(cid)d.contentId=Number(cid);if(f.get('taskId'))d.taskId=f.get('taskId');if(f.get('revisionId'))d.revisionId=f.get('revisionId');try{await mutate('/drive',d,'POST','Drive link connected');onDone();}catch{}}}><Field label="Link title"><input name="title" required placeholder="Brand assets, first cut, or shoot references…"/></Field><Field label="Google Drive URL"><input type="url" name="url" required placeholder="https://drive.google.com/…"/></Field><div className="form-grid"><Field label="Client"><select required value={client} onChange={e=>{setClient(e.target.value);setCid('');}}><option value="">Choose a client</option>{clients?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Content"><select value={cid} onChange={e=>setCid(e.target.value)}><option value="">Client-level link</option>{content?.filter(c=>c.clientId===client).map(c=><option key={c.id} value={c.id}>{c.code} · {c.title}</option>)}</select></Field><Field label="Category"><select name="category">{['Brand Asset','Reference','Script','Raw Footage','Final Video','Graphic','Document','Report','Other'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Task (optional)"><select name="taskId"><option value="">No task</option>{tasks?.filter(t=>t.clientId===client&&(!cid||t.contentId===Number(cid))).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field></div><Field label="Revision ID (optional)"><input name="revisionId" placeholder="Connect to a specific revision"/></Field><label className="checkbox-label"><input type="checkbox" name="clientVisible"/> Make this link visible to the client</label><div className="info-note">Your media stays in Google Drive. Agency OS stores the link and its context.</div><FormFooter pending={pending} onCancel={onDone} submit="Add Drive link"/></form>;
}
function UserForm({initial,onDone}:{initial?:any;onDone:()=>void}){
 const {actor}=useApp(),{mutate,pending}=useMutation(),{data:roles}=useResource<any[]>('/roles'),{data:clients}=useResource<any[]>('/clients');
 const [role,setRole]=useState(initial?.roleId||'');
 const [avatarUrl,setAvatarUrl]=useState<string|null>(initial?.avatarUrl||null);
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d:any={name:f.get('name'),email:f.get('email'),roleId:role,avatarUrl,phone:f.get('phone')||'',whatsapp:f.get('whatsapp')||'',whatsappOptIn:f.get('whatsappOptIn')==='on'};if(initial?.id)d.active=f.get('active')==='on';else{d.password=f.get('password');if(f.get('clientId'))d.clientId=f.get('clientId');}try{await mutate(initial?.id?'/users/'+initial.id:'/users',d,initial?.id?'PATCH':'POST',initial?.id?'Team member updated':'Account created');onDone();}catch{}}}><ImageUploadField label="Profile photo" value={avatarUrl} onChange={setAvatarUrl} name={initial?.name||'Team member'} hint="Displayed on tasks, comments, conversations, and header"/><div className="form-grid"><Field label="Full name"><input name="name" required minLength={2} defaultValue={initial?.name}/></Field><Field label="Email"><input name="email" type="email" required defaultValue={initial?.email}/></Field><Field label="Role"><select required value={role} onChange={e=>setRole(e.target.value)}><option value="">Choose a role</option>{roles?.filter(r=>!r.isSuperAdmin||actor.isSuperAdmin).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>{!initial?.id&&<Field label="Temporary password"><input name="password" type="password" minLength={12} required autoComplete="new-password"/></Field>}<Field label="Phone"><input name="phone" type="tel" defaultValue={initial?.phone}/></Field><Field label="WhatsApp number"><input name="whatsapp" type="tel" defaultValue={initial?.whatsapp}/></Field></div>{!initial?.id&&roles?.find(r=>r.id===role)?.isClient&&<Field label="Client workspace"><select name="clientId" required><option value="">Choose a client</option>{clients?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>}<label className="checkbox-label"><input type="checkbox" name="whatsappOptIn" defaultChecked={initial?.whatsappOptIn}/> This person has opted in to WhatsApp notifications</label>{initial?.id&&<label className="checkbox-label"><input type="checkbox" name="active" defaultChecked={initial.active}/> Account active</label>}<p className="muted">New users must change their temporary password when they first sign in. Share access details securely.</p><FormFooter pending={pending} onCancel={onDone} submit={initial?.id?'Save team member':'Create account'}/></form>;
}
function ProfileForm({onDone}:{onDone:()=>void}){
 const {actor,refresh}=useApp(),{mutate,pending}=useMutation();
 const [avatarUrl,setAvatarUrl]=useState<string|null>(actor.avatarUrl||null);
 const [name,setName]=useState(actor.name);
 return <form onSubmit={async e=>{e.preventDefault();try{await mutate('/auth/profile',{avatarUrl,name},'PATCH','Profile updated');refresh();onDone();}catch{}}}><ImageUploadField label="Your profile photo" value={avatarUrl} onChange={setAvatarUrl} name={name} hint="Visible in your sidebar, comments, team directory, and header"/><div className="form-grid"><Field label="Your name"><input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></Field><Field label="Email"><input value={actor.email} disabled className="opacity-70 cursor-not-allowed"/></Field></div><FormFooter pending={pending} onCancel={onDone} submit="Save profile"/></form>;
}

